# Generated by Django 4.1.6 on 2023-02-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STSSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование статуса')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.DateTimeField(verbose_name='Время посещения СТО'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='STSSite.status'),
        ),
    ]
