# Generated by Django 4.1.6 on 2023-02-16 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STSSite', '0002_status_alter_order_time_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='uslugi',
            options={'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 7, 29, 11, 209185, tzinfo=datetime.timezone.utc), verbose_name='Дата посещения СТО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.TimeField(verbose_name='Время посещения СТО'),
        ),
    ]
