# Generated by Django 4.1.6 on 2023-02-19 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('STSSite', '0003_alter_order_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='cat',
            field=models.CharField(default='кузовные работы', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата посещения СТО'),
        ),
    ]
