# Generated by Django 4.1.6 on 2023-02-19 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('STSSite', '0004_uslugi_cat_alter_order_date_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_to',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='STSSite.status'),
        ),
    ]
